import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { resolve, join } from 'node:path';

const home = mkdtempSync(join(tmpdir(), 'finishbit-catalog-'));
try {
  const binary = resolve(process.argv.slice(2).find(arg => !arg.startsWith('--')) || (process.platform === 'win32' ? 'fnsh.exe' : 'fnsh'));
  const catalog = JSON.parse(execFileSync(binary, ['capabilities', '--json'], { encoding: 'utf8', env: { ...process.env, FINISHBIT_HOME: home } }));
  catalog.sort((a, b) => a.id.localeCompare(b.id, 'en'));
  const content = '// Generated by scripts/website-catalog.mjs from the application registry.\nconst finishbitCatalog = ' + JSON.stringify(catalog, null, 2) + ';\n';
  const target = resolve('website/catalog.js');
  if (process.argv.includes('--check')) {
    if (readFileSync(target, 'utf8').replace(/\r\n/g, '\n') !== content) throw new Error('Website catalog is stale. Build fnsh and run node scripts/website-catalog.mjs.');
  } else {
    writeFileSync(target, content);
  }
  console.log(`Website catalog: ${catalog.length} Operations; ${process.argv.includes('--check') ? 'verified' : 'updated'}.`);
} finally {
  rmSync(home, { recursive: true, force: true });
}
