const repo = 'https://github.com/fu9zhou/finish-bit';
const install = 'go install github.com/fu9zhou/finish-bit/cmd/fnsh@latest';
const copyIcon = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><rect x="8" y="8" width="12" height="12" rx="2"/><path d="M15 8V4H4v11h4"/></svg>';
const esc = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let lang;
try { lang = localStorage.getItem('finishbit-language'); } catch {}
if (!['zh','en'].includes(lang)) {
  const locale = navigator.languages?.[0] || navigator.language || 'en';
  const region = locale.split('-').slice(1).find(x => /^[A-Z]{2}$/i.test(x))?.toUpperCase();
  lang = /^zh/i.test(locale) || region === 'CN' ? 'zh' : 'en';
}
const t = (en,zh) => lang === 'zh' ? zh : en;
let filter = 'all';
const topics = [
  ['start','Quick start','快速开始'],['install','Installation','安装与升级'],['discovery','Discover Operations','发现能力'],['execute','Execute & output','执行与输出'],['media','Media processing','音视频处理'],['agents','Agent integration','Agent 集成'],['extensions','Extensions','扩展开发']
];
const operations = [
  ['json.format','{ }','data','Format JSON with a consistent, readable structure.','格式化 JSON，让数据结构清晰可读。','Core'],
  ['text.replace','Aa','data','Replace text with explicit, reusable rules.','按明确规则替换文本，告别重复脚本。','Core'],
  ['file.info','⌁','files','Inspect file metadata before the next step.','读取文件元数据，为下一步操作做好准备。','Core'],
  ['image.resize','▧','files','Resize PNG and JPEG images proportionally.','等比例缩放 PNG 与 JPEG 图片。','Core'],
  ['video.trim','▷','media','Keep the part you need. Leave the rest behind.','精准裁剪视频，只保留需要的片段。','FFmpeg'],
  ['csv.to-json','⊞','data','Turn tabular CSV into structured JSON.','将 CSV 表格转换为结构化 JSON。','Core']
];
function copyButton(value) {return `<button class="copy" data-copy="${esc(value)}" aria-label="${t('Copy command','复制命令')}">${copyIcon}</button>`;}
function code(value,caption='Terminal') {return `<div class="codebox"><span class="codecaption">${caption}</span>${copyButton(value)}<pre><code>${esc(value)}</code></pre></div>`;}
function header(docs) {return `<a class="skip" href="#main">${t('Skip to content','跳转到正文')}</a><header class="header"><nav class="nav wrap" aria-label="${t('Main navigation','主导航')}"><a class="brand" href="#/"><span class="logo" aria-hidden="true">F.</span>FinishBit</a><div class="navlinks"><a class="${!docs?'active':''}" href="#/">${t('Overview','概览')}</a><a href="#/operations">${t('Operations','能力目录')}</a><a class="${docs?'active':''}" href="#/docs/start">${t('Documentation','使用说明')}</a><a href="${repo}/blob/main/CHANGELOG.md" target="_blank" rel="noopener">${t('Changelog','更新日志')} ↗</a></div><div class="navright"><select id="language" class="language" aria-label="${t('Language','选择语言')}"><option value="en" ${lang==='en'?'selected':''}>EN · English</option><option value="zh" ${lang==='zh'?'selected':''}>中 · 简体中文</option></select><a class="github" href="${repo}" target="_blank" rel="noopener">GitHub ↗</a></div></nav></header>`;}
function footer(){return `<footer class="footer"><div class="wrap footerinner"><span><b>FinishBit</b> &nbsp; / &nbsp; ${t('Small bits. Real progress.','小小能力，步步完成。')}</span><div class="footerlinks"><a href="${repo}">GitHub ↗</a><a href="${repo}/blob/main/LICENSE">AGPL-3.0</a><a href="${repo}/issues">${t('Feedback','反馈建议')} ↗</a></div><span>${t('Built for agents. Open to everyone.','为 Agent 而生，向所有人开放。')}</span></div></footer>`;}
function cards(){return operations.filter(o=>filter==='all'||o[2]===filter).map(o=>`<a class="card" href="#/docs/${o[2]==='media'?'media':'discovery'}"><div class="cardtop"><span class="icon" aria-hidden="true">${o[1]}</span><span class="tag">${o[5]}</span></div><h3>${o[0]}</h3><p>${t(o[3],o[4])}</p><div class="cardbottom"><span>${t('Explore operation','了解此能力')}</span><span aria-hidden="true">↗</span></div></a>`).join('');}
function home(){return `<main id="main" tabindex="-1"><div class="wrap"><section class="hero"><div><a class="eyebrow release" href="${repo}/releases"><span class="dot"></span>${t('Open source. Ready to build.','开源构建 · 即刻开始')}<span aria-hidden="true">↗</span></a><h1>${t('Finish more.<br><span>Rewrite less.</span>','多完成，<br><span>少重写。</span>')}</h1><p>${t('Small, reusable building blocks for AI tasks.<br>Give your agents the tools to finish the job — without writing the same script twice.','为 AI 任务准备的小型可复用能力。<br>让 Agent 用已有工具完成任务，不必一遍遍重写相同的脚本。')}</p><div class="actions"><a class="button primary" href="#/docs/start">${t('Start building','快速开始')}<span>→</span></a><a class="button" href="${repo}">${t('View on GitHub','查看 GitHub')}<span>↗</span></a></div><div class="install"><span>$</span><code>${install}</code>${copyButton(install)}</div></div><div class="terminal" aria-label="${t('Illustrative CLI workflow','CLI 工作流示例')}"><div class="terminalbar"><i></i><i></i><i></i><span>fnsh — ${t('your next task, finished','下一个任务，已完成')}</span></div><div class="terminalbody"><div class="comment"># 01 ${t('Find the right building block','找到合适的能力')}</div><div class="cmd"><span class="prompt">❯</span>fnsh search "trim video"</div><div class="result"><strong>video.trim</strong> &nbsp; <small>ffmpeg</small><br><small>${t('Trim a video by start time and duration.','按开始时间与时长裁剪视频。')}</small></div><div class="comment"># 02 ${t('Inspect the contract','查看输入与选项')}</div><div class="cmd"><span class="prompt">❯</span>fnsh describe video.trim</div><div class="comment"># 03 ${t('Run it. Finish it.','执行能力，完成任务。')}</div><div class="cmd"><span class="prompt">❯</span>fnsh video trim input.mp4<br>&nbsp; --start 10s --duration 20s -o clip.mp4</div><div class="success">✓ clip.mp4 &nbsp; <small>${t('Task complete.','任务完成。')}</small></div></div><div class="terminalfoot"><span>● ${t('LOCAL EXECUTION','本地执行')}</span><span>${t('DEMO · FFMPEG REQUIRED','工作流示例 · 需要 FFmpeg')}</span></div></div></section><div class="trust"><span><b>⌘</b> Windows · macOS · Linux</span><span><b>{ }</b> ${t('Structured JSON output','结构化 JSON 输出')}</span><span><b>◇</b> ${t('One Go binary','单个 Go 二进制')}</span><span><b>↗</b> ${t('Open source · AGPL-3.0','开源 · AGPL-3.0')}</span></div><section class="section"><div class="sectionhead"><div><span class="kicker">01 / ${t('THE WORKFLOW','工作方式')}</span><h2>${t('A little discovery. A lot less work.','先发现能力，再轻松完成。')}</h2></div><p>${t('Your agent decides what to do.<br>FinishBit takes care of how it gets done.','Agent 决定做什么，<br>FinishBit 负责把它做好。')}</p></div><div class="steps">${[
['01',t('Search with intent','按意图搜索'),t('Find a focused set of Operations for the task at hand.','用自然语言找到当前任务需要的少量能力。'),'fnsh search "trim video"'],
['02',t('Understand the contract','查看能力契约'),t('Inspect typed inputs, options and runtime requirements.','了解输入类型、可用选项和运行时要求。'),'fnsh describe video.trim'],
['03',t('Execute with confidence','执行并获取结果'),t('Run an existing implementation. Get structured results.','调用已有实现，获得可供程序处理的结构化结果。'),'fnsh run --request request.json --json']
].map(s=>`<div class="step"><span class="number">${s[0]} /</span><h3>${s[1]}</h3><p>${s[2]}</p><code>${s[3]}</code></div>`).join('')}</div></section></div><section class="catalog section" id="operations"><div class="wrap"><div class="sectionhead"><div><span class="kicker">02 / ${t('THE BUILDING BLOCKS','能力单元')}</span><h2>${t('Common tasks. Already handled.','常见任务，已有答案。')}</h2><p>${t('From a small JSON fix to your next video workflow.','从一次 JSON 格式化，到下一段视频工作流。')}</p></div><a class="textlink" href="#/docs/discovery">${t('Explore the full catalog','探索完整能力目录')} →</a></div><div class="filters" role="group" aria-label="${t('Filter operations','筛选能力')}">${[['all','All operations','全部能力'],['data','JSON & text','JSON 与文本'],['files','Files & images','文件与图片'],['media','Video & audio','音视频']].map(f=>`<button class="filter" data-filter="${f[0]}" aria-pressed="${filter===f[0]}">${t(f[1],f[2])}</button>`).join('')}</div><div class="cards" id="cards">${cards()}</div></div></section><section class="section wrap split"><div><span class="kicker">03 / ${t('AGENT NATIVE','为 AGENT 而生')}</span><h2>${t('Less glue code.<br>More getting things done.','少写衔接代码，<br>多做真正的工作。')}</h2><p class="intro">${t('A predictable interface from discovery to execution. Built for the way agents work, useful wherever you automate.','从发现到执行，始终如一的调用方式。为 Agent 的工作方式设计，也适合你的自动化流程。')}</p><ul class="checklist"><li>${t('Typed inputs and structured errors','强类型输入与结构化错误')}</li><li>${t('Progressive discovery, focused context','渐进式发现，节省上下文')}</li><li>${t('Language-neutral local extensions','语言无关的本地扩展')}</li></ul><a class="textlink" href="#/docs/agents">${t('Connect your agent','接入你的 Agent')} →</a></div><div>${code(JSON.stringify({operation:'text.replace',inputs:['hello world','world','FinishBit'],options:{count:1}},null,2),'request.json')}<div class="install"><code>fnsh run --request request.json --json</code>${copyButton('fnsh run --request request.json --json')}</div></div></section><div class="wrap"><section class="cta"><div><h2>${t('Your next task has a head start.','下一个任务，从已有能力开始。')}</h2><p>${t('Install fnsh. Find a bit. Finish the task.','安装 fnsh，找到能力，完成任务。')}</p></div><a class="button light" href="#/docs/start">${t('Get started','开始使用')} →</a></section></div></main>`;}
function docContent(id){
const note = (en,zh) => `<div class="note">${t(en,zh)}</div>`;
switch(id){
case 'install': return `<p class="lead">${t('Choose a release archive or build from source. FinishBit runs on Windows, macOS and Linux, on amd64 and arm64.','选择版本归档或从源码安装。支持 Windows、macOS、Linux，以及 amd64 和 arm64。')}</p><h2>${t('Install with Go','使用 Go 安装')}</h2><p>${t('Requires Go 1.25.13 or later. Add the Go binary directory to PATH.','需要 Go 1.25.13 或更新版本，请将 Go 二进制目录加入 PATH。')}</p>${code(install+'\nfnsh version\nfnsh doctor')}<h2>${t('Release archives','下载版本归档')}</h2><p>${t('Download the archive for your system and checksums.txt from GitHub Releases. Verify the SHA-256 checksum, then extract fnsh (fnsh.exe on Windows) to a directory on PATH.','从 GitHub Releases 下载与你系统匹配的归档及 checksums.txt。核验 SHA-256 后，将 fnsh（Windows 为 fnsh.exe）解压到 PATH 中的目录。')}</p><a class="button" href="${repo}/releases">${t('Open releases','查看发布版本')} ↗</a><h2>${t('Upgrade & remove','升级与卸载')}</h2><p>${t('To upgrade, rerun go install with the desired version or replace the binary with a new release archive. To uninstall, remove the binary; runtime data is stored separately in your user configuration directory under finishbit.','升级时重新运行 go install 并指定目标版本，或用新版本归档替换二进制。卸载时删除二进制即可；运行时数据单独存储在用户配置目录中的 finishbit 下。')}</p>${note('Before upgrading pre-1.0 versions, review the compatibility policy and changelog.','升级 1.0 前的版本时，请先阅读兼容性政策与更新日志。')}`;
case 'discovery':return `<p class="lead">${t('An Operation is a focused, reusable capability. Discover its identifier first, then inspect the exact contract before execution.','Operation 是一个专注、可复用的能力。先找到能力标识，再查看确切契约，最后执行。')}</p><h2>${t('Search by intent','按意图搜索')}</h2>${code('fnsh search "trim video" --limit 3 --json')}<p>${t('Search matches identifiers, summaries, aliases and tags. The default limit is five results.','搜索匹配标识、摘要、别名和标签，默认返回五条结果。')}</p><h2>${t('Read the contract','读取契约')}</h2>${code('fnsh describe video.trim --json')}<p>${t('Inspect input types, options, defaults, provider and runtime requirements. Always use the live contract from your installed binary.','查看输入类型、选项、默认值、Provider 和运行时要求。以本机已安装版本返回的契约为准。')}</p><h2>${t('List every capability','列出所有能力')}</h2>${code('fnsh capabilities --json')}<p>${t('The catalog includes core Operations, managed providers and installed extensions.','能力目录包含内置 Operation、托管 Provider 和已安装扩展。')}</p>`;
case 'execute':return `<p class="lead">${t('Use readable commands in your terminal and structured requests in automation. Both resolve to the same application service.','在终端中使用易读命令，在自动化中使用结构化请求，两者调用相同的应用服务。')}</p><h2>${t('Direct commands','直接调用')}</h2>${code('fnsh json format data.json --indent 2\nfnsh run json.format data.json --indent 2')}<h2>${t('Structured requests','结构化请求')}</h2>${code(JSON.stringify({operation:'text.replace',inputs:['hello world','world','FinishBit'],options:{count:1}},null,2),'request.json')}${code('fnsh run --request request.json --json')}${note('Paths in a request resolve relative to your current working directory. Do not combine --request with positional Operation arguments or extra Operation options.','请求中的路径相对于当前工作目录解析。不要将 --request 与位置参数或额外的 Operation 选项混用。')}<h2>${t('Output & exit codes','输出与退出码')}</h2><p>${t('With --json, success is one JSON value on stdout. Structured errors go to stderr. Branch on error.code instead of parsing messages.','使用 --json 时，成功结果作为一个 JSON 值写入 stdout，结构化错误写入 stderr。请根据 error.code 分支处理，不要解析错误文案。')}</p><table><thead><tr><th>${t('Exit code','退出码')}</th><th>${t('Meaning','含义')}</th></tr></thead><tbody>${[['0',t('Success','成功')],['1',t('Execution, integrity or platform failure','执行、完整性或平台错误')],['2',t('Invalid input or unknown Operation','无效输入或未知 Operation')],['3',t('Required managed package missing','缺少所需托管包')]].map(x=>`<tr><td><code>${x[0]}</code></td><td>${x[1]}</td></tr>`).join('')}</tbody></table>`;
case 'media':return `<p class="lead">${t('Trim and compress video or extract audio with a managed FFmpeg provider. The runtime is installed only when you need it.','通过托管 FFmpeg Provider 裁剪、压缩视频或提取音频。运行时按需安装。')}</p><h2>${t('1. Install the provider','1. 安装 Provider')}</h2>${code('fnsh pkg add ffmpeg\nfnsh doctor')}<p>${t('FinishBit downloads a pinned runtime and verifies its checksum before activation.','FinishBit 下载固定版本的运行时，并在启用前验证其校验和。')}</p><h2>${t('2. Inspect and trim','2. 查看契约并裁剪')}</h2>${code('fnsh describe video.trim\nfnsh video trim input.mp4 --start 10s --duration 20s -o clip.mp4')}<p>${t('This example starts at 10 seconds and keeps a 20-second clip.','此示例从第 10 秒开始，保留 20 秒片段。')}</p><h2>${t('3. Discover more media tools','3. 发现更多媒体工具')}</h2>${code('fnsh search "compress video"\nfnsh search "extract audio"')}`;
case 'agents':return `<p class="lead">${t('Give your agent a shared vocabulary for discovery, contracts and execution. The bundled Skill teaches the workflow.','让 Agent 用统一方式发现能力、读取契约和执行任务。仓库自带的 Skill 提供完整工作流程。')}</p><h2>${t('Add the FinishBit Skill','添加 FinishBit Skill')}</h2><p>${t('Copy or link skills/finishbit from the repository into the Skill directory supported by your agent host. Install fnsh and make it available on PATH in the same environment.','将仓库中的 skills/finishbit 复制或链接到 Agent 宿主支持的 Skill 目录，并确保同一环境中已安装 fnsh 且可通过 PATH 调用。')}</p><a class="button" href="${repo}/tree/main/skills/finishbit">${t('View the Agent Skill','查看 Agent Skill')} ↗</a><h2>${t('The agent workflow','Agent 工作流程')}</h2>${code('fnsh search "format json" --json\nfnsh describe json.format --json\nfnsh json format data.json --indent 2 --json')}${note('The Skill is an adapter. Every Operation still runs locally through fnsh and the shared application service.','Skill 是适配层，所有 Operation 仍通过本地 fnsh 和统一应用服务执行。')}<p>${t('Prefer structured results, inspect required runtimes, and handle errors by code. For larger integrations, submit request.json through fnsh run --request.','优先使用结构化输出、检查所需运行时，并按错误码处理失败。更复杂的集成可以通过 fnsh run --request 提交 request.json。')}</p>`;
case 'extensions':return `<p class="lead">${t('Bring your own building blocks. Any executable can publish Operations through the versioned local JSON protocol.','添加你自己的能力单元。任意可执行程序都可以通过版本化本地 JSON 协议发布 Operation。')}</p><h2>${t('Package your extension','准备扩展')}</h2><p>${t('An extension directory or ZIP contains a finishbit-extension.json manifest and an executable. Start with the repository’s echo example for the exact manifest and protocol.','扩展目录或 ZIP 中包含 finishbit-extension.json 清单和可执行程序。可从仓库中的 echo 示例了解准确的清单格式与协议。')}</p><a class="button" href="${repo}/tree/main/examples/extensions/echo">${t('Explore the example','查看扩展示例')} ↗</a><h2>${t('Install and discover','安装并发现')}</h2>${code('fnsh ext add ./my-extension\nfnsh ext ls\nfnsh search "my capability"')}${note('Extensions run as local third-party programs with your permissions. Review their source and provenance before installation.','扩展以你的权限作为本地第三方程序运行。安装前请审查其源码和来源。')}<h2>${t('Inspect the protocol','查看协议')}</h2><p><a class="textlink" href="${repo}/blob/main/docs/extension-protocol.md">${t('Read the extension protocol v1','阅读扩展协议 v1')} ↗</a></p>`;
default:return `<p class="lead">${t('From your first install to your first finished task. All you need is a terminal and a small building block.','从第一次安装，到完成第一个任务。打开终端，从一个小小的能力单元开始。')}</p>${note('FinishBit is in active development before v1.0. Core Operations run locally with no resident service.','FinishBit 正处于 v1.0 前的积极开发阶段。核心 Operation 本地执行，无须常驻服务。')}<h2>${t('1. Install fnsh','1. 安装 fnsh')}</h2><p>${t('With Go 1.25.13 or later installed, run:','安装 Go 1.25.13 或更新版本后，运行：')}</p>${code(install)}<p>${t('Prefer a prebuilt binary?','希望使用预编译版本？')} <a class="textlink" href="#/docs/install">${t('See all installation options','查看完整安装方式')} →</a></p><h2>${t('2. Check your environment','2. 检查运行环境')}</h2>${code('fnsh version\nfnsh doctor')}<h2>${t('3. Discover an Operation','3. 发现一个能力')}</h2>${code('fnsh search "format json"\nfnsh describe json.format')}<h2>${t('4. Finish your first task','4. 完成第一个任务')}</h2><p>${t('Create a data.json file with the following content:','创建 data.json 文件，写入以下内容：')}</p>${code('{"hello":"FinishBit","ready":true}','data.json')}${code('fnsh json format data.json --indent 2')}<p>${t('Add --json when an agent or automation needs a machine-readable result.','当 Agent 或自动化需要机器可读结果时，加上 --json。')}</p>`;
}}
function docs(id){const topic=topics.find(x=>x[0]===id)||topics[0];return `<main class="wrap docs" id="main" tabindex="-1"><aside class="sidebar"><label for="docsearch">${t('Find a guide','查找使用指南')}</label><input id="docsearch" type="search" placeholder="${t('Search documentation…','搜索使用说明…')}"><nav class="sidenav" aria-label="${t('Documentation topics','文档主题')}">${topics.map(x=>`<a class="${x[0]===topic[0]?'active':''}" ${x[0]===topic[0]?'aria-current="page"':''} data-topic="${x.join(' ').toLowerCase()}" href="#/docs/${x[0]}">${t(x[1],x[2])}</a>`).join('')}</nav><p id="noresults" class="empty" hidden>${t('No matching guide. Try another term.','没有匹配的指南，请换个关键词。')}</p></aside><article class="article"><span class="kicker">${t('DOCUMENTATION / '+topic[1],'使用说明 / '+topic[2])}</span><h1>${t(topic[1],topic[2])}</h1>${docContent(topic[0])}<div class="docnext"><a class="button" href="#/docs/${topics[(topics.indexOf(topic)+1)%topics.length][0]}">${t('Next: '+topics[(topics.indexOf(topic)+1)%topics.length][1],'下一篇：'+topics[(topics.indexOf(topic)+1)%topics.length][2])} →</a></div></article></main>`;}
function render(){const path=location.hash.slice(1)||'/';const isDocs=path.startsWith('/docs');document.documentElement.lang=lang==='zh'?'zh-CN':'en';document.body.classList.toggle('zh',lang==='zh');document.title=isDocs?`${t('Documentation','使用说明')} — FinishBit`:`FinishBit — ${t('Finish more. Rewrite less.','多完成，少重写。')}`;document.querySelector('#app').innerHTML=header(isDocs)+(isDocs?docs(path.split('/')[2]):home())+footer();if(path==='/operations')requestAnimationFrame(()=>document.querySelector('#operations').scrollIntoView());}
document.addEventListener('change',e=>{if(e.target.id==='language'){lang=e.target.value;try{localStorage.setItem('finishbit-language',lang)}catch{}const y=scrollY;render();scrollTo(0,y);document.querySelector('#language').focus({preventScroll:true});}});
document.addEventListener('input',e=>{if(e.target.id==='docsearch'){const query=e.target.value.trim().toLowerCase();let count=0;document.querySelectorAll('[data-topic]').forEach(a=>{a.hidden=!a.dataset.topic.includes(query);a.style.display=a.hidden?'none':'';if(!a.hidden)count++});document.querySelector('#noresults').hidden=count>0;}});
let toastTimer;
document.addEventListener('click',async e=>{const skip=e.target.closest('.skip');if(skip){e.preventDefault();document.querySelector('#main').focus();document.querySelector('#main').scrollIntoView();return;}const button=e.target.closest('[data-copy]');if(button){let message;try{await navigator.clipboard.writeText(button.dataset.copy);message=t('Copied to clipboard','已复制到剪贴板')}catch{message=t('Copy unavailable. Select and copy the command.','无法自动复制，请选中命令后复制。')}const toast=document.querySelector('#toast');toast.textContent=message;toast.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('visible'),2300)}const tab=e.target.closest('[data-filter]');if(tab){filter=tab.dataset.filter;document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b===tab)));document.querySelector('#cards').innerHTML=cards();}});
addEventListener('hashchange',()=>{render();if(location.hash!=='#/operations')scrollTo(0,0);document.querySelector('#main').focus({preventScroll:true});});
render();
