const repo = 'https://github.com/fu9zhou/finish-bit';
const install = 'go install github.com/fu9zhou/finish-bit/cmd/fnsh@latest';
const copyIcon = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><rect x="8" y="8" width="12" height="12" rx="2"/><path d="M15 8V4H4v11h4"/></svg>';
const iconPaths = {
  github: '<path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3.3-.4 6.8-1.6 6.8-7A5.4 5.4 0 0 0 19.4 3.7 5 5 0 0 0 19.3.2S18.2-.2 15 1.8a13.4 13.4 0 0 0-7 0C4.8-.2 3.7.2 3.7.2A5 5 0 0 0 3.6 3.7a5.4 5.4 0 0 0-1.4 3.8c0 5.4 3.5 6.6 6.8 7A4.8 4.8 0 0 0 8 18v4"/><path d="M8 19c-3 .9-3-1.5-4-2"/>',
  file: '<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><path d="M14 2v6h6M8 13h8M8 17h6"/>',
  tag: '<path d="M20.6 13.4 11 3.8A2 2 0 0 0 9.6 3H4a1 1 0 0 0-1 1v5.6A2 2 0 0 0 3.8 11l9.6 9.6a2 2 0 0 0 2.8 0l4.4-4.4a2 2 0 0 0 0-2.8z"/><circle cx="7.5" cy="7.5" r="1"/>',
  monitor: '<rect x="2" y="3" width="20" height="14" rx="2"/><path d="M8 21h8M12 17v4"/>',
  code: '<path d="m8 9-3 3 3 3M16 9l3 3-3 3M14 5l-4 14"/>',
  package: '<path d="m12 3 8 4.5v9L12 21l-8-4.5v-9zM4.5 7.8 12 12l7.5-4.2M12 12v9"/>',
  branch: '<circle cx="6" cy="4" r="2"/><circle cx="18" cy="6" r="2"/><circle cx="6" cy="20" r="2"/><path d="M6 6v12M18 8a6 6 0 0 1-6 6H6"/>',
  table: '<rect x="3" y="4" width="18" height="16" rx="2"/><path d="M3 10h18M9 4v16"/>',
  folder: '<path d="M3 6a2 2 0 0 1 2-2h5l2 2h7a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/>',
  image: '<rect x="3" y="3" width="18" height="18" rx="2"/><circle cx="8.5" cy="8.5" r="1.5"/><path d="m21 15-5-5L5 21"/>',
  archive: '<path d="M4 4h16v5H4zM5 9h14v11H5zM10 13h4"/>',
  video: '<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m10 9 5 3-5 3z"/>',
};
const icon = (name,className='ui-icon') => `<svg class="${className}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${iconPaths[name]}</svg>`;
const esc = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let lang;
try { lang = localStorage.getItem('finishbit-language'); } catch {}
if (!['zh','en'].includes(lang)) {
  const locale = navigator.languages?.[0] || navigator.language || 'en';
  const region = locale.split('-').slice(1).find(x => /^[A-Z]{2}$/i.test(x))?.toUpperCase();
  lang = /^zh/i.test(locale) || region === 'CN' ? 'zh' : 'en';
}
const t = (en,zh) => lang === 'zh' ? zh : en;
let filter = 'all';
let operationQuery = '';
const addedIn016Operations = new Set(["biology.blood-types","calendar.lunar","calendar.solar","cidr.inspect","code.hello","color.convert","contact.extract","cron.next","crypto.decrypt","crypto.encrypt","crypto.key","date.add","date.age","date.business-days","date.diff","date.expiry","disk.capacity","document.compare","document.compress","document.scan","finance.compound","finance.contributions","finance.mortgage","health.bmi","hex.decode","hex.encode","html.decode","html.encode","image.ascii","image.color-at","image.filter","image.hide","image.id-photo","image.minimum-bytes","image.palette","image.pixelate","image.reveal","image.solid","image.split-grid","image.target-size","ip.inspect","json.diff","json.to-toml","json.to-yaml","jwt.decode","markdown.mindmap","markdown.to-html","math.evaluate","math.statistics","name.generate","number.base","number.chinese","ocr.text","ocr.to-html","ocr.to-pdf","ocr.words","password.generate","password.inspect","pdf.compress-images","pdf.metadata-set","pdf.ocr","pdf.ocr-text","pdf.page-numbers","pdf.rasterize","pdf.resize-pages","pdf.sign-image","pdf.to-docx","pdf.to-long-image","pdf.to-pptx","qrcode.contact","qrcode.decode","qrcode.generate","random.choose","random.integer","regex.match","regex.replace","regex.validate","screen.record","speech.synthesize","speech.voices","temperature.convert","text.case","text.chinese","text.diff","text.emoticons","text.hide","text.led","text.map","text.normalize","text.pinyin","text.reveal","text.reverse","time.world","toml.format","toml.to-json","toml.validate","unicode.decode","unicode.encode","unit.convert","url.parse","useragent.parse","worksheet.handwriting","xml.format","xml.validate","yaml.format","yaml.to-json","yaml.validate"]);
const topics = [
  ['start','Quick start','快速开始'],['install','Install & upgrade','安装与升级'],['troubleshooting','Troubleshooting','常见问题'],['execute','CLI & automation','CLI 与自动化'],['extensions','Extensions','扩展开发']
];
const capabilityGuides = {
  media: ['Media workflows','音视频用法','media'], pdf: ['PDF workflows','PDF 用法','pdf'],
  images: ['Image workflows','图片用法','images'], tables: ['Table workflows','表格用法','data'],
  documents: ['Document workflows','文档用法','documents'], archives: ['Archive workflows','压缩包用法','archives'],
  local: ['Local tools & limits','本地工具与限制','all']
};
const categoryGuideIds = {data:'tables',files:'local',images:'images',pdf:'pdf',documents:'documents',archives:'archives',media:'media'};
const categories = [['all','All operations','全部能力'],['data','JSON & tables','JSON 与表格'],['files','Files & utilities','文件与工具'],['images','Images','图片'],['pdf','PDF','PDF'],['documents','Documents','文档'],['archives','Archives','压缩包'],['media','Video & audio','音视频']];
const categoryDescriptions = {
  data: ['Transform structured data and text.','转换结构化数据与文本。'],
  files: ['Inspect files and handle everyday utilities.','检查文件并处理常用工具任务。'],
  images: ['Convert, compose and inspect raster images.','转换、组合与检查位图。'],
  pdf: ['Read, edit, render and reorganize PDFs.','读取、编辑、渲染与重组 PDF。'],
  documents: ['Convert and structure documents with Pandoc.','使用 Pandoc 转换与组织文档。'],
  archives: ['Create, inspect and safely extract archives.','创建、检查并安全解压文件。'],
  media: ['Process video, audio, subtitles and previews.','处理视频、音频、字幕与预览。']
};
const categoryIcons = {images:'image',pdf:'file',documents:'file',archives:'archive',media:'video',data:'table',files:'folder'};
const categorySubtitles = {data:'DATA',files:'UTILITIES',images:'IMAGING',pdf:'PDF',documents:'DOCUMENTS',archives:'ARCHIVES',media:'MEDIA'};
function category(o) { if(/^(qrcode|ocr)\./.test(o.id))return 'images';if(/^(document|worksheet|markdown)\./.test(o.id))return 'documents';if(/^(speech|screen)\./.test(o.id))return 'media';if(/^(yaml|toml|xml)\./.test(o.id))return 'data';return o.source === '7zip' ? 'archives' : o.source === 'pandoc' ? 'documents' : o.id.startsWith('pdf.') ? 'pdf' : o.id.startsWith('image.') ? 'images' : o.source === 'ffmpeg' ? 'media' : /^(json|jsonl|csv|text)\./.test(o.id) ? 'data' : 'files'; }
const operations = finishbitCatalog;
function guide(o) { if(addedIn016Operations.has(o.id))return 'local'; if(o.source==='qsv')return 'tables';return ({pdf:'pdf',images:'images',media:'media',documents:'documents',archives:'archives'})[category(o)] || 'execute'; }
function addedIn014(o) { return !addedIn016Operations.has(o.id) && o.source !== 'core' && !['video.trim','video.compress','audio.extract'].includes(o.id); }
function updatedIn015(o) { return ['pdf.extract-text','document.split'].includes(o.id); }
function copyButton(value,label=t('Copy command','复制命令')) {return `<button class="copy" data-copy="${esc(value)}" aria-label="${esc(label)}">${copyIcon}</button>`;}
function code(value,caption='Terminal') {return `<div class="codebox"><span class="codecaption">${caption}</span>${copyButton(value)}<pre><code>${esc(value)}</code></pre></div>`;}
function agentInstallPrompt(){return t(
  `Please follow the installation instructions at ${repo} to download and install the complete skills/finishbit Skill directory for your agent host and the fnsh CLI for this system, add fnsh to PATH, and verify the setup with fnsh version and fnsh doctor.`,
  `请按 ${repo} 的安装说明，下载并安装完整的 skills/finishbit 技能目录到你支持的技能位置，以及适合当前系统的 fnsh CLI，配置 PATH，并通过 fnsh version 和 fnsh doctor 验证安装。`
);}
function agentInstallCard(){
  const prompt=agentInstallPrompt();
  const formatted=esc(prompt).replace(esc(repo),`<a class="prompt-source" href="${repo}" target="_blank" rel="noopener">${esc(repo)}</a>`).replace(/skills\/finishbit|fnsh version|fnsh doctor|PATH/g,match=>`<code>${match}</code>`);
  return `<div class="agent-install-card"><div class="agent-install-heading">${icon('code')}<span>${t('Installation prompt','安装指令')}</span></div><p class="agent-install-prompt">${formatted}</p><div class="agent-install-footer"><span>${t('Paste into your AI chat.','复制后，发送给 AI')}</span><button class="button primary" data-copy="${esc(prompt)}">${copyIcon}${t('Copy prompt','复制指令')}</button></div></div>`;
}
function header(routeName) {const inCatalog=['catalog','operation','guide'].includes(routeName);const docs=routeName==='docs';return `<a class="skip" href="#main">${t('Skip to content','跳转到正文')}</a><header class="header"><nav class="nav wrap" aria-label="${t('Main navigation','主导航')}"><a class="brand" href="#/"><span class="logo" aria-hidden="true">F.</span>FinishBit</a><div class="navlinks"><a class="${routeName==='home'?'active':''}" ${routeName==='home'?'aria-current="page"':''} href="#/">${t('Overview','概览')}</a><a class="${inCatalog?'active':''}" ${inCatalog?'aria-current="page"':''} href="#/operations">${t('Operations','能力目录')}</a><a class="${docs?'active':''}" ${docs?'aria-current="page"':''} href="#/docs/start">${t('Guides','使用指南')}</a><a class="icon-link" href="${repo}/blob/main/CHANGELOG.md" target="_blank" rel="noopener">${icon('file')}${t('Changelog','更新日志')}</a></div><div class="navright"><select id="language" class="language" aria-label="${t('Language','选择语言')}"><option value="en" ${lang==='en'?'selected':''}>EN · English</option><option value="zh" ${lang==='zh'?'selected':''}>中 · 简体中文</option></select><a class="github icon-link" href="${repo}" target="_blank" rel="noopener">${icon('github')}GitHub</a></div></nav></header>`;}
function footer(){return `<footer class="footer"><div class="wrap footerinner"><span><b>FinishBit</b> &nbsp; / &nbsp; ${t('A practical partner for your AI.','给你的 AI，一个靠谱的好助手。')}</span><div class="footerlinks"><a class="icon-link" href="${repo}">${icon('github')}GitHub</a><a class="icon-link" href="${repo}/blob/main/LICENSE">${icon('branch')}AGPL-3.0</a><a class="icon-link" href="${repo}/issues">${icon('file')}${t('Feedback','反馈建议')}</a></div><span>${t('Built for agents. Open to everyone.','为 Agent 而生，向所有人开放。')}</span></div></footer>`;}
function visibleOperations(){const terms=operationQuery.trim().toLowerCase().split(/\s+/).filter(Boolean);return operations.filter(o=>{const haystack=[o.id,o.summary,...(o.aliases||[]),...(o.tags||[])].join(' ').toLowerCase();return(filter==='all'||category(o)===filter)&&terms.every(term=>haystack.includes(term));});}
function operationTag(o){if(addedIn016Operations.has(o.id))return esc(o.source)+' · v0.1.6';if(updatedIn015(o))return `${esc(o.source)} · v0.1.5`;return `${esc(o.source)}${addedIn014(o)?' · v0.1.4':''}`;}
function cards(){return visibleOperations().map(o=>{
  const name=t(o.summary,o.aliases?.find(x=>/[\u3400-\u9fff]/.test(x))||o.summary);
  return `<a class="card" href="${esc(catalogContextURL('/operations/'+encodeURIComponent(o.id)))}" aria-label="${esc(name+' — '+o.id)}"><div class="cardtop"><span class="icon" aria-hidden="true">${icon(categoryIcons[category(o)])}</span><span class="tag">${operationTag(o)}</span></div><h3>${esc(name)}</h3><p class="operation-id" translate="no"><code>${esc(o.id)}</code></p></a>`;
}).join('');}
function categoryOverview(){return categories.slice(1).map(item=>{const count=operations.filter(o=>category(o)===item[0]).length;const description=categoryDescriptions[item[0]];return `<a class="category-card" href="#/operations?category=${item[0]}"><div class="category-card-top"><span class="category-mark">${icon(categoryIcons[item[0]])}</span><span class="category-count">${count} OPS</span></div><span class="category-subtitle">${categorySubtitles[item[0]]}</span><h3>${t(item[1],item[2])}</h3><p>${t(description[0],description[1])}</p><span class="category-link">${t('Browse','查看')} →</span></a>`;}).join('');}
function operationPage(id) {
  const o=operations.find(x=>x.id===id);
  if(!o)return `<main id="main" class="wrap article" tabindex="-1"><h1>${t('Operation not found','未找到能力')}</h1><a href="#/operations">${t('Browse the catalog','查看能力目录')}</a></main>`;
  const releaseNote=addedIn016Operations.has(o.id)?t('Available since v0.1.6. See the local tools guide for supported platforms and limits.','自 v0.1.6 起提供。支持平台和能力限制请查阅本地工具说明。'):updatedIn015(o)?t('Updated in v0.1.5 with paragraph-aware text output.','v0.1.5 更新了段落感知的文本输出。'):addedIn014(o)?t('Available since v0.1.4. Install required packages before use.','自 v0.1.4 起提供，使用前请安装所需依赖。'):t('Inspect your installed CLI for the current contract.','以本机 CLI 返回的契约为准。');
  return `<main id="main" class="wrap article" tabindex="-1"><a class="back-link" href="${esc(catalogURL())}">← ${t('Back to operations','返回能力目录')}</a><h1 translate="no">${esc(o.id)}</h1><p class="lead">${esc(t(o.summary,o.aliases?.find(x=>/[\u3400-\u9fff]/.test(x))||o.summary))}</p>${o.description?`<h2>${t('Behavior & limits','行为与限制')}</h2><p lang="en">${esc(o.description)}</p>`:''}${o.id==='screen.record'?`<div class="note">${t('Windows only. Records silent video for up to 300 seconds.','仅支持 Windows，录制无声视频，最长 300 秒。')}</div>`:''}<div class="note">${releaseNote}</div><p>${t('Provider','提供方')}: ${esc(o.source)}</p>${code('fnsh describe '+o.id+' --json')}<h2>${t('Required packages','所需依赖')}</h2>${o.requirements?.length?code(o.requirements.map(r=>'fnsh pkg add '+r.package).join('\n')):`<p>${t('No package required for the default engine.','默认引擎无须额外依赖。')}</p>`}<p><a class="textlink" href="${capabilityGuides[guide(o)]?esc(catalogContextURL('/operations/guides/'+guide(o),finishbitRoutes.parseHash(location.hash,topics.map(x=>x[0])).query.has('category')?filter:category(o))):'#/docs/execute'}">${t('Usage and platform support','使用方法与平台支持')} →</a></p><h2>${t('Inputs & options','输入与选项')}</h2>${code(JSON.stringify({inputs:o.inputs||[],options:o.options||[]},null,2),'Operation contract')}</main>`;
}
function catalogResults(){const list=visibleOperations();return list.length?cards():`<p class="empty catalog-empty">${t('No operations match this search.','没有匹配的能力，请调整搜索或分类。')}</p>`;}
function catalogGuideLink(){
  const id=categoryGuideIds[filter];
  if(!id)return '';
  const guide=capabilityGuides[id];
  return `<a class="catalog-guide-link" href="${esc(catalogContextURL('/operations/guides/'+id))}"><span><strong>${t(guide[0],guide[1])}</strong><span>${t('Examples, required tools and platform limits','查看示例、依赖安装与平台限制')}</span></span><span aria-hidden="true">↗</span></a>`;
}
function capabilityGuidePage(id){
  const guide=capabilityGuides[id];
  const relatedCategory=finishbitRoutes.parseHash(location.hash,topics.map(x=>x[0])).query.has('category')?filter:guide[2];
  const backURL=catalogContextURL('/operations',relatedCategory);
  return `<main id="main" class="wrap capability-guide" tabindex="-1"><article class="article"><a class="back-link" href="${esc(backURL)}">← ${t('Back to related capabilities','返回相关能力')}</a><h1>${t(guide[0],guide[1])}</h1>${capabilityGuideContent(id)}<div class="docnext"><a class="button" href="${esc(backURL)}">${t('Browse related capabilities','浏览相关能力')}</a></div></article></main>`;
}
function catalogPage(){const count=visibleOperations().length;return `<main id="main" tabindex="-1"><section class="catalog-hero wrap"><h1>${t('Find a tool for the task.','找到任务需要的能力')}</h1><p>${t('Search by name or task, then explore examples and requirements.','按名称或任务搜索，查看具体用法和运行要求。')}</p></section><section class="catalog-browser wrap"><div class="catalog-toolbar"><label class="sr-only" for="operationSearch">${t('Search operations','搜索能力')}</label><input id="operationSearch" type="search" autocomplete="off" value="${esc(operationQuery)}" placeholder="${t('Search operations…','搜索名称或关键词…')}"><span id="catalogCount" role="status">${t(`${count} operations`,`${count} 项能力`)}</span></div><div class="filters" role="group" aria-label="${t('Filter operations','筛选能力')}">${categories.map(f=>`<button class="filter" data-filter="${f[0]}" aria-pressed="${filter===f[0]}">${t(f[1],f[2])}</button>`).join('')}</div><div id="catalogGuide">${catalogGuideLink()}</div><div class="cards" id="cards">${catalogResults()}</div></section></main>`;}
function notFoundPage(){return `<main id="main" class="wrap article not-found" tabindex="-1"><span class="kicker">404 / ${t('NOT FOUND','未找到')}</span><h1>${t('This route does not exist.','这个页面不存在。')}</h1><p class="lead">${t('Return to the overview, browse Operations, or open the documentation.','返回概览、浏览能力目录，或打开使用说明。')}</p><div class="actions"><a class="button primary" href="#/">${t('Overview','概览')}</a><a class="button" href="#/operations">${t('Operations','能力目录')}</a></div></main>`;}
function capabilityGuideContent(id){
const note = (en,zh) => `<div class="note">${t(en,zh)}</div>`;
switch(id){
case 'local': return `<p class="lead">${t('Use QR, text, OCR and local document tools with clear output limits.','使用二维码、文字、OCR 和本地文档工具，并了解输出边界。')}</p>${note('Processing stays on your computer; optional engines download only during installation.','文件处理全部在用户本地完成，可选引擎仅在安装时下载。')}${code('fnsh search "二维码" --json\nfnsh run qrcode.generate "FinishBit" --output qr.png\nfnsh pkg add tesseract\nfnsh run ocr.text scan.png --language chi_sim+eng --json')}<p>${t('Includes text and format tools, calculations, QR codes, image utilities, printed-text OCR and document workflows. Word output is reflowed text, PPT output is page images, and OCR is not specialized handwriting or document-field recognition.','包含文字与格式处理、计算、二维码、图片工具、印刷文字 OCR 和文档流程。Word 输出为文字重排，PPT 输出为每页图片；OCR 不等于手写或证件字段专用识别。')}</p><p>${t('Windows speech uses installed voices. Recording is explicit, silent and limited in duration. FinishBit v0.1.7 pins Tesseract 5.5.3 for Windows x64; the engine and Chinese/English models take about 103.3 MiB.','Windows 语音使用已有系统声音。录屏需显式执行，无声且限制时长。FinishBit v0.1.7 固定 Windows x64 Tesseract 5.5.3，中英文 OCR 引擎与模型约 103.3 MiB。')}</p><a class="textlink" href="${repo}/blob/main/docs/local-tools.md">${t('Full local toolbox guide and limits','完整本地工具说明与限制')} ↗</a>`;
case 'media':return `<p class="lead">${t('Process video and audio with managed FFmpeg tools.','使用托管 FFmpeg 工具处理视频与音频。')}</p>${note('Managed FFmpeg/ffprobe 6.1.1 are pinned; Windows x64 is tested.','托管 FFmpeg/ffprobe 固定为 6.1.1，已完成 Windows x64 实测。')}${code('fnsh pkg add ffmpeg\nfnsh pkg add ffprobe\nfnsh media info input.mp4 --json\nfnsh video concat first.mp4 --files second.mp4 -o joined.mp4\nfnsh audio normalize input.wav --lufs -16 -o normalized.wav')}<p>${t('Also includes frame extraction, GIFs, contact sheets, watermarking, subtitle extraction/burning, mixing, silence detection/removal and waveforms. Outputs require explicit overwrite.','还包括抽帧、GIF、联系表、水印、字幕提取/烧录、混音、静音检测/移除和波形图。覆盖已有输出须显式指定。')}</p><a class="textlink" href="${repo}/blob/main/docs/media.md">${t('Full media guide','完整音视频说明')} ↗</a>`;
case 'pdf':return `<p class="lead">${t('Combine PDFs, extract readable text and render page previews.','合并 PDF、提取可读文字，并生成页面预览。')}</p>${note('Use --unwrap when PDF visual lines should become logical paragraphs. It also rejoins words split by end-of-line hyphenation. Scans still need OCR.','当 PDF 的视觉行需要还原为逻辑段落时使用 --unwrap；它也会重新连接因行尾连字符而拆开的单词。扫描件仍需 OCR。')}${code('fnsh pkg add pdfcpu\nfnsh pkg add poppler\nfnsh pdf merge cover.pdf --files report.pdf -o merged.pdf\nfnsh pdf extract-text merged.pdf --unwrap -o text.txt\nfnsh pdf render merged.pdf --first 1 --last 3 -o preview')}<p>${t('Unwrap is opt-in because poetry, code and fixed-layout text may depend on physical line breaks. It cannot be combined with --layout.','合并换行为可选能力，因为诗歌、代码和固定版式文本可能依赖物理换行；不能与 --layout 同时使用。')}</p><a class="textlink" href="${repo}/blob/main/docs/pdf.md">${t('Full PDF guide','完整 PDF 说明')} ↗</a>`;
case 'images':return `<p class="lead">${t('Choose the built-in image engine or ImageMagick for your task.','按任务选择内置图片引擎或 ImageMagick。')}</p>${note('The enhanced engine adds formats and editing. Managed ImageMagick supports Windows x64/arm64; installation acquires an official extraction helper when needed. The arm64 helper uses Windows x86 emulation; real acceptance currently covers x64.','增强引擎补充格式与编辑能力，托管 ImageMagick 支持 Windows x64/arm64，安装时按需获取官方解包助手。arm64 的助手使用 Windows x86 仿真，真实验收目前覆盖 x64。')}${code('fnsh pkg add imagemagick\nfnsh image formats --json\nfnsh image convert photo.png --engine imagemagick -o photo.webp\nfnsh image crop photo.png --width 100 --height 100 -o crop.png\nfnsh image contact-sheet first.png --files second.png --columns 2 -o grid.png')}<p>${t('Includes orientation correction, transparency, text/watermarks, color adjustment, difference images, GIF creation/splitting and icons. Supported codecs depend on the installed build.','包括方向校正、透明处理、文字/水印、调色、差异图、GIF 生成/拆帧及图标。编解码格式以安装构建为准。')}</p><a class="textlink" href="${repo}/blob/main/docs/image-enhancements.md">${t('Full image guide','完整图片说明')} ↗</a>`;
case 'archives':return `<p class="lead">${t('Create, inspect and extract archives with managed 7-Zip.','使用托管 7-Zip 创建、检查和解压文件。')}</p>${note('Managed 7-Zip Extra 26.03 currently supports Windows x64. Installation automatically acquires the official extraction helper when needed. Eight write formats are supported; ZIP and 7z support encryption and updates. RAR is not available in this standalone build.','托管 7-Zip Extra 26.03 当前支持 Windows x64，安装时会按需自动下载官方解包助手。支持 8 种写入格式，ZIP 和 7z 支持加密与更新。此独立构建不提供 RAR。')}${code('fnsh pkg add 7zip\nfnsh archive create reports --format zip -o reports.zip\nfnsh archive list reports.zip --json\nfnsh archive test reports.zip --json\nfnsh archive extract reports.zip --entries reports/summary.txt -o extracted\nfnsh archive repack reports.zip --to tar.xz -o reports.tar.xz\nfnsh archive volumes reports --volume-mib 10 -o parts')}<p>${t('Extraction validates paths and sizes before publishing a new directory. Mutation produces a new archive; existing outputs need explicit overwrite. Password options name an environment variable.','解压先检查路径和大小，再发布新目录。更新类操作生成新的压缩包，覆盖已有结果需显式指定。密码选项填写环境变量名。')}</p><a class="textlink" href="${repo}/blob/main/docs/archives.md">${t('Full archive guide','完整压缩包说明')} ↗</a>`;
case 'documents':return `<p class="lead">${t('Convert documents and extract text with Pandoc.','使用 Pandoc 转换文档并提取文字。')}</p>${note('document.split defaults to --wrap none so Pandoc does not insert visual line breaks into generated TXT sections. Use --wrap auto only when you explicitly want wrapped output.','document.split 默认使用 --wrap none，避免 Pandoc 在生成的 TXT 分段中插入视觉换行。仅在明确需要折行输出时使用 --wrap auto。')}${code('fnsh pkg add pandoc\nfnsh document formats --json\nfnsh document convert report.md --to docx -o report.docx\nfnsh document text report.docx -o report.txt\nfnsh document inspect report.docx --json\nfnsh document split report.md --level 1 --wrap none -o chapters')}<p>${t('Inputs are local. External images are not fetched; embed images as data URIs or use an office document with embedded media. PDF engines and arbitrary filters are not exposed.','输入文件在本地处理。外部图片不会自动读取，可使用数据 URI 或已内嵌图片的 Office 文档。不开放 PDF 排版引擎和任意过滤器。')}</p><a class="textlink" href="${repo}/blob/main/docs/documents.md">${t('Full document guide','完整文档说明')} ↗</a>`;
case 'tables':return `<p class="lead">${t('Clean and transform tables with the core tools and managed qsv.','使用内置工具和托管 qsv 清洗、转换表格。')}</p>${note('Install managed qsv for the expanded group; the first supported target is Windows x64.','扩充能力需安装托管 qsv，首个支持平台为 Windows x64。')}${code('fnsh pkg add qsv\nfnsh csv select orders.csv --columns id --columns amount -o selected.csv\nfnsh csv deduplicate orders.csv --columns id --keep first -o unique.csv\nfnsh csv stats orders.csv --columns amount -o stats.csv\nfnsh csv split orders.csv --rows 500 -o chunks')}<p>${t('Use exact column names. Outputs are staged and existing files require explicit overwrite. Inputs stay local; remote schemas and script execution are not exposed.','使用精确列名。结果先暂存，覆盖已有文件需显式指定。数据在本地处理，不开放远程规则和脚本执行。')}</p><a class="textlink" href="${repo}/blob/main/docs/tables.md">${t('Full table guide','完整表格说明')} ↗</a>`;

default:return "";
}}
function docContent(id){
const note = (en,zh) => `<div class="note">${t(en,zh)}</div>`;
switch(id){
case 'troubleshooting':return `<p class="lead">${t('Start with the environment check, then follow the issue that matches your result.','先检查运行环境，再按遇到的问题处理。')}</p>${code('fnsh version\nfnsh doctor')}<h2>${t('The command cannot be found','提示找不到 fnsh 命令')}</h2><p>${t('Confirm the CLI is installed and its directory is on PATH in the environment where your agent runs. Reopen the terminal or agent after updating PATH.','确认 CLI 已安装，并且二进制所在目录已加入 Agent 运行环境的 PATH。更新 PATH 后重新打开终端或 Agent。')}</p><a class="textlink" href="#/docs/install">${t('Installation instructions','查看安装说明')}</a><h2>${t('The agent does not discover the Skill','Agent 没有识别到 Skill')}</h2><p>${t('Install the entire skills/finishbit directory, including references, in the skill location supported by your host. Some hosts need a new conversation to discover it.','确认安装的是完整的 skills/finishbit 目录（含 references），并位于宿主支持的技能目录。部分宿主需要新开对话才能识别。')}</p><a class="textlink" href="#/docs/start">${t('Quick start and manual Agent setup','快速开始与手动 Agent 配置')}</a><h2>${t('A required tool is missing','提示缺少依赖工具')}</h2><p>${t('Inspect the operation contract and install only the package it requires. A successful CLI installation does not install every optional tool.','先查看能力契约，再安装它需要的依赖。安装 CLI 并不意味着已经安装所有可选工具。')}</p>${code('fnsh describe video.trim --json\nfnsh pkg add ffmpeg')}<p>${t('This example installs FFmpeg for video trimming; use the package named by your own operation.','上例为视频裁剪安装 FFmpeg；其他任务以对应能力返回的依赖为准。')}</p><h2>${t('The platform or output is not what you expected','平台不支持，或结果与预期不一致')}</h2><p>${t('Read the capability’s inputs and limits in the catalog. External tools have platform requirements; OCR, PDF-to-Word and PDF-to-slides also have output limits. Check the original input and inspect the actual result.','在能力目录中查看输入要求与使用限制。外部工具有平台要求，OCR、PDF 转 Word 和 PDF 转幻灯片也有输出边界。请检查原始输入与实际结果。')}</p><a class="textlink" href="#/operations">${t('Find the capability','查找对应能力')}</a><h2>${t('Still stuck?','仍然无法解决？')}</h2><p>${t('Include the CLI version, operating system, operation ID and error message when reporting an issue. Remove private file contents and credentials.','反馈时附上 CLI 版本、操作系统、能力 ID 和错误信息，并移除私人文件内容与凭据。')}</p><a class="button" href="${repo}/issues">${t('Report an issue','反馈问题')}</a>`;
case 'install': return `<p class="lead">${t('Choose a release archive or build from source. FinishBit runs on Windows, macOS and Linux, on amd64 and arm64.','选择版本归档或从源码安装。支持 Windows、macOS、Linux，以及 amd64 和 arm64。')}</p><h2>${t('Install with Go','使用 Go 安装')}</h2><p>${t('Requires Go 1.25.13 or later. Add the Go binary directory to PATH.','需要 Go 1.25.13 或更新版本，请将 Go 二进制目录加入 PATH。')}</p>${code(install+'\nfnsh version\nfnsh doctor')}<h2>${t('Release archives','下载版本归档')}</h2><p>${t('Download the archive for your system and checksums.txt from GitHub Releases. Verify the SHA-256 checksum, then extract fnsh (fnsh.exe on Windows) to a directory on PATH.','从 GitHub Releases 下载与你系统匹配的归档及 checksums.txt。核验 SHA-256 后，将 fnsh（Windows 为 fnsh.exe）解压到 PATH 中的目录。')}</p><a class="button" href="${repo}/releases">${t('Open releases','查看发布版本')} ↗</a><h2>${t('Optional tools','可选工具')}</h2><p>${t('Install only the tools required by your operation. Runtime packages use fixed versions and SHA-256 checks. In v0.1.7, 7z installation reuses managed 7-Zip or downloads the official standalone helper automatically; no system-wide 7-Zip installation is required.','按能力需求安装可选工具。运行时使用固定版本并校验 SHA-256。v0.1.7 会在安装 7z 包时复用托管 7-Zip，或自动下载官方独立助手，无须预先安装系统级 7-Zip。')}</p>${code('fnsh pkg info tesseract\nfnsh pkg add tesseract\nfnsh pkg repair tesseract')}<p>${t('The installed CLI determines package versions. After upgrading the CLI, use pkg add to install its registered version; use pkg repair for a damaged package.','依赖版本由已安装的 CLI 决定。升级 CLI 后，使用 pkg add 安装其登记版本；依赖损坏时使用 pkg repair 修复。')}</p><a class="textlink" href="${repo}/blob/main/docs/package-management.md">${t('Package versions and supported platforms','依赖版本与支持平台')} ↗</a><h2>${t('Upgrade & remove','升级与卸载')}</h2><p>${t('To upgrade, rerun go install with the desired version or replace the binary with a new release archive. To uninstall, remove the binary; runtime data is stored separately in your user configuration directory under finishbit.','升级时重新运行 go install 并指定目标版本，或用新版本归档替换二进制。卸载时删除二进制即可；运行时数据单独存储在用户配置目录中的 finishbit 下。')}</p>${note('Before upgrading pre-1.0 versions, review the compatibility policy and changelog.','升级 1.0 前的版本时，请先阅读兼容性政策与更新日志。')}`;
case 'execute':return `<p class="lead">${t('An Operation is a focused, reusable capability. Discover its identifier first, then inspect the exact contract before execution.','Operation 是一个专注、可复用的能力。先找到能力标识，再查看确切契约，最后执行。')}</p><h2>${t('Search by intent','按意图搜索')}</h2>${code('fnsh search "trim video" --limit 3 --json')}<p>${t('Search matches identifiers, summaries, aliases and tags. The default limit is five results.','搜索匹配标识、摘要、别名和标签，默认返回五条结果。')}</p><h2>${t('Read the contract','读取契约')}</h2>${code('fnsh describe video.trim --json')}<p>${t('Inspect input types, options, defaults, provider and runtime requirements. Always use the live contract from your installed binary.','查看输入类型、选项、默认值、Provider 和运行时要求。以本机已安装版本返回的契约为准。')}</p><h2>${t('List every capability','列出所有能力')}</h2>${code('fnsh capabilities --json')}<p>${t('The catalog includes core Operations, managed providers and installed extensions.','能力目录包含内置 Operation、托管 Provider 和已安装扩展。')}</p><p class="lead">${t('Use readable commands in your terminal and structured requests in automation. Both resolve to the same application service.','在终端中使用易读命令，在自动化中使用结构化请求，两者调用相同的应用服务。')}</p><h2>${t('Direct commands','直接调用')}</h2>${code('fnsh json format data.json --indent 2\nfnsh run json.format data.json --indent 2')}<h2>${t('Structured requests','结构化请求')}</h2>${code(JSON.stringify({operation:'text.replace',inputs:['hello world','world','FinishBit'],options:{count:1}},null,2),'request.json')}${code('fnsh run --request request.json --json')}${note('Paths in a request resolve relative to your current working directory. Do not combine --request with positional Operation arguments or extra Operation options.','请求中的路径相对于当前工作目录解析。不要将 --request 与位置参数或额外的 Operation 选项混用。')}<h2>${t('Output & exit codes','输出与退出码')}</h2><p>${t('With --json, success is one JSON value on stdout. Structured errors go to stderr. Branch on error.code instead of parsing messages.','使用 --json 时，成功结果作为一个 JSON 值写入 stdout，结构化错误写入 stderr。请根据 error.code 分支处理，不要解析错误文案。')}</p><table><thead><tr><th>${t('Exit code','退出码')}</th><th>${t('Meaning','含义')}</th></tr></thead><tbody>${[['0',t('Success','成功')],['1',t('Execution, integrity or platform failure','执行、完整性或平台错误')],['2',t('Invalid input or unknown Operation','无效输入或未知 Operation')],['3',t('Required managed package missing','缺少所需托管包')]].map(x=>`<tr><td><code>${x[0]}</code></td><td>${x[1]}</td></tr>`).join('')}</tbody></table>`;
case 'extensions':return `<p class="lead">${t('Bring your own building blocks. Any executable can publish Operations through the versioned local JSON protocol.','添加你自己的能力单元。任意可执行程序都可以通过版本化本地 JSON 协议发布 Operation。')}</p><h2>${t('Package your extension','准备扩展')}</h2><p>${t('An extension directory or ZIP contains a finishbit-extension.json manifest and an executable. Start with the repository’s echo example for the exact manifest and protocol.','扩展目录或 ZIP 中包含 finishbit-extension.json 清单和可执行程序。可从仓库中的 echo 示例了解准确的清单格式与协议。')}</p><a class="button" href="${repo}/tree/main/examples/extensions/echo">${t('Explore the example','查看扩展示例')} ↗</a><h2>${t('Install and discover','安装并发现')}</h2>${code('fnsh ext add ./my-extension\nfnsh ext ls\nfnsh search "my capability"')}${note('Extensions run as local third-party programs with your permissions. Review their source and provenance before installation.','扩展以你的权限作为本地第三方程序运行。安装前请审查其源码和来源。')}<h2>${t('Inspect the protocol','查看协议')}</h2><p><a class="textlink" href="${repo}/blob/main/docs/extension-protocol.md">${t('Read the extension protocol v1','阅读扩展协议 v1')} ↗</a></p>`;
default:return `<p class="lead">${t('One sentence to your AI. It installs the Skill and CLI for you.','给 AI 一句话，让它帮你装好 Skill 和 CLI。')}</p>${agentInstallCard()}<p>${t('Paste it into an agent that can download files and run local commands. Follow any installation permissions requested by your agent.','把它粘贴给能够下载文件、运行本地命令的 Agent，并按宿主提示完成必要的安装授权。')}</p><h2>${t('What your AI will set up','AI 会帮你完成什么')}</h2><ul><li>${t('Read the repository installation guide and choose the CLI release for your operating system and architecture.','阅读仓库安装说明，选择匹配当前系统与架构的 CLI 发行版。')}</li><li>${t('Install the complete skills/finishbit directory, including its references, in the location supported by your agent.','将完整的 skills/finishbit 目录（含参考文件）安装到当前 Agent 支持的技能位置。')}</li><li>${t('Make fnsh available on PATH, run fnsh version and fnsh doctor, and report the results.','配置 fnsh 的 PATH，运行 fnsh version 和 fnsh doctor，并报告验证结果。')}</li></ul><p>${t('Some hosts load newly installed Skills in a new conversation. Optional runtimes are installed only when a task needs them.','部分宿主需要在新对话中加载刚安装的 Skill；可选运行时在任务需要时再安装。')}</p><h2>${t('Then give it a task','然后，直接交给它一个任务')}</h2><blockquote class="first-task">${t('Use FinishBit to format this JSON: {"hello":"FinishBit","ready":true}.','用 FinishBit 把这段 JSON 格式化：{"hello":"FinishBit","ready":true}。')}</blockquote><p>${t('The Skill guides your AI to discover an operation, inspect its contract and execute it locally.','Skill 会引导 AI 先发现能力、检查契约，再在本地执行。')}</p><details class="manual-agent"><summary>${t('Manual Agent setup','手动配置 Agent')}</summary><h2>${t('Manual Skill setup','手动配置 Skill')}</h2><p>${t('Copy or link skills/finishbit from the repository into the Skill directory supported by your agent host. Install fnsh and make it available on PATH in the same environment.','将仓库中的 skills/finishbit 复制或链接到 Agent 宿主支持的 Skill 目录，并确保同一环境中已安装 fnsh 且可通过 PATH 调用。')}</p><a class="button" href="${repo}/tree/main/skills/finishbit">${t('View the Agent Skill','查看 Agent Skill')} ↗</a></details><div class="actions"><a class="button" href="#/operations">${t('Explore capabilities','探索能力')}</a><a class="button" href="#/docs/install">${t('Install manually','手动安装')}</a></div>`;
}}
function docs(id){
  const topic=topics.find(item=>item[0]===id)||topics[0];
  const groups=[['Using FinishBit','使用指南',topics.slice(0,3)],['For developers','开发者文档',topics.slice(3)]];
  const next=topics[topics.indexOf(topic)+1];
  return `<main class="wrap docs" id="main" tabindex="-1"><aside class="sidebar"><nav class="sidenav" aria-label="${t('Guide navigation','指南导航')}">${groups.map(([en,zh,items])=>`<div class="guide-nav-group"><p class="guide-nav-label">${t(en,zh)}</p>${items.map(item=>`<a class="${item[0]===topic[0]?'active':''}" ${item[0]===topic[0]?'aria-current="page"':''} href="#/docs/${item[0]}">${t(item[1],item[2])}</a>`).join('')}</div>`).join('')}<a class="guide-catalog-link" href="#/operations">${t('Browse all capabilities','查找具体能力')} ↗</a></nav></aside><article class="article"><h1>${t(topic[1],topic[2])}</h1>${docContent(topic[0])}${next?`<div class="docnext"><a class="button" href="#/docs/${next[0]}">${t('Next: '+next[1],'下一篇：'+next[2])} →</a></div>`:''}</article></main>`;
}
function catalogContextURL(path,selectedCategory=filter){const params=new URLSearchParams();params.set('category',selectedCategory);if(operationQuery.trim())params.set('q',operationQuery.trim());return '#'+path+'?'+params.toString();}
function catalogURL(){const params=new URLSearchParams();if(filter!=='all')params.set('category',filter);if(operationQuery.trim())params.set('q',operationQuery.trim());const query=params.toString();return '#/operations'+(query?'?'+query:'');}
let headerSizeObserver;
function syncHeaderHeight(){
  headerSizeObserver?.disconnect();
  const siteHeader=document.querySelector('.header');
  if(!siteHeader)return;
  const update=()=>document.documentElement.style.setProperty('--site-header-height',`${siteHeader.getBoundingClientRect().height}px`);
  update();
  if(typeof ResizeObserver!=='undefined'){
    headerSizeObserver=new ResizeObserver(update);
    headerSizeObserver.observe(siteHeader);
  }
}
function render(){const route=finishbitRoutes.parseHash(location.hash,topics.map(x=>x[0]));if(route.redirect){const query=route.query.toString();history.replaceState(null,'','#'+route.redirect+(query?'?'+query:''));}const requestedFilter=route.query.get('category');filter=categories.some(x=>x[0]===requestedFilter)?requestedFilter:'all';operationQuery=['catalog','operation','guide'].includes(route.name)?(route.query.get('q')||''):'';document.documentElement.lang=lang==='zh'?'zh-CN':'en';document.body.classList.toggle('zh',lang==='zh');let content;let title;if(route.name==='home'){content=homePage();title=t('Fewer tokens. Work, delivered.','省下 token，把事情做稳。')}else if(route.name==='catalog'){content=catalogPage();title=t('Operation catalog','能力目录')}else if(route.name==='operation'){content=operationPage(route.id);title=operations.some(o=>o.id===route.id)?route.id:t('Operation not found','未找到能力')}else if(route.name==='guide'){content=capabilityGuidePage(route.topic);title=t(...capabilityGuides[route.topic].slice(0,2))}else if(route.name==='docs'){content=docs(route.topic);title=t('Guides','使用指南')}else{content=notFoundPage();title='404'}document.title=`${title} — FinishBit`;document.querySelector('#app').innerHTML=header(route.name)+content+footer();syncHeaderHeight();}
document.addEventListener('change',e=>{if(e.target.id==='language'){lang=e.target.value;try{localStorage.setItem('finishbit-language',lang)}catch{}const y=scrollY;render();scrollTo(0,y);document.querySelector('#language').focus({preventScroll:true});}});
document.addEventListener('input',e=>{if(e.target.id==='operationSearch'){operationQuery=e.target.value;history.replaceState(null,'',catalogURL());const list=visibleOperations();document.querySelector('#catalogGuide').innerHTML=catalogGuideLink();document.querySelector('#cards').innerHTML=catalogResults();document.querySelector('#catalogCount').textContent=t(`${list.length} operations`,`${list.length} 项能力`);}});
let toastTimer;
document.addEventListener('click',async e=>{const skip=e.target.closest('.skip');if(skip){e.preventDefault();document.querySelector('#main').focus();document.querySelector('#main').scrollIntoView();return;}const button=e.target.closest('[data-copy]');if(button){let message;try{await navigator.clipboard.writeText(button.dataset.copy);message=t('Copied to clipboard','已复制到剪贴板')}catch{message=t('Copy unavailable. Select and copy the command.','无法自动复制，请选中命令后复制。')}const toast=document.querySelector('#toast');toast.textContent=message;toast.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('visible'),2300)}const tab=e.target.closest('[data-filter]');if(tab){filter=tab.dataset.filter;history.replaceState(null,'',catalogURL());document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b===tab)));const list=visibleOperations();document.querySelector('#catalogGuide').innerHTML=catalogGuideLink();document.querySelector('#cards').innerHTML=catalogResults();document.querySelector('#catalogCount').textContent=t(`${list.length} operations`,`${list.length} 项能力`);}});
addEventListener('hashchange',()=>{render();scrollTo(0,0);document.querySelector('#main').focus({preventScroll:true});});
render();
